/*
* Copyright (c) 2005 - 2010 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:  Macro definition file for logging.
*
*/

// Autogenerated from .\phoneloggerviewcommands.st by the stringtable tool - Do not edit
#include <e32std.h>
#include <stringpool.h>
#include <stringtablesupport.h>
#include "phoneloggerviewcommands.h"
#ifdef _DEBUG
#undef _DEBUG
#endif

_STLIT8(K1, "EPhoneViewStartValue");
_STLIT8(K2, "EPhoneViewRemoveNumberEntry");
_STLIT8(K3, "EPhoneViewSetNumberEntryVisible");
_STLIT8(K4, "EPhoneViewGetNumberFromEntry");
_STLIT8(K5, "EPhoneViewGetNumberEntryCount");
_STLIT8(K6, "EPhoneViewGetNumberEntryIsUsedStatus");
_STLIT8(K7, "EPhoneViewGetNumberEntryIsVisibleStatus");
_STLIT8(K8, "EPhoneViewClearNumberEntryContent");
_STLIT8(K9, "EPhoneViewCreateCallHeader");
_STLIT8(K10, "EPhoneViewCreateEmergencyCallHeader");
_STLIT8(K11, "EPhoneViewUpdateCallHeaderRemoteInfoData");
_STLIT8(K12, "EPhoneViewUpdateCallHeaderCallDuration");
_STLIT8(K13, "EPhoneViewRemoveCallHeader");
_STLIT8(K14, "EPhoneViewUpdateCba");
_STLIT8(K15, "EPhoneViewUpdateBubble");
_STLIT8(K16, "EPhoneViewActivateAudioPathUIChanges");
_STLIT8(K17, "EPhoneViewActivateAudioAvailabilityUIChanges");
_STLIT8(K18, "EPhoneViewActivateMuteUIChanges");
_STLIT8(K19, "EPhoneViewShowNote");
_STLIT8(K20, "EPhoneViewShowGlobalNote");
_STLIT8(K21, "EPhoneViewShowProgressNote");
_STLIT8(K22, "EPhoneViewRemoveNote");
_STLIT8(K23, "EPhoneViewRemoveProgressNote");
_STLIT8(K24, "EPhoneViewRemoveGlobalNote");
_STLIT8(K25, "EPhoneViewShowQuery");
_STLIT8(K26, "EPhoneViewSetListQueryString");
_STLIT8(K27, "EPhoneViewRemoveQuery");
_STLIT8(K28, "EPhoneViewBringAppToForeground");
_STLIT8(K29, "EPhoneViewSendToBackground");
_STLIT8(K30, "EPhoneViewGetTopApplicationIsDisplayedStatus");
_STLIT8(K31, "EPhoneViewGetForegroundApplication");
_STLIT8(K32, "EPhoneViewStartCapturingKey");
_STLIT8(K33, "EPhoneViewStopCapturingKey");
_STLIT8(K34, "EPhoneViewSetGlobalNotifiersDisabled");
_STLIT8(K35, "EPhoneViewOpenSingleItemFetchDialog");
_STLIT8(K36, "EPhoneViewRemovePhoneDialogs");
_STLIT8(K37, "EPhoneViewCreateConference");
_STLIT8(K38, "EPhoneViewAddToConference");
_STLIT8(K39, "EPhoneViewRemoveFromConference");
_STLIT8(K40, "EPhoneViewPrivateFromConference");
_STLIT8(K41, "EPhoneViewSelectedConfMember");
_STLIT8(K42, "EPhoneViewGetCallIdByState");
_STLIT8(K43, "EPhoneViewGetCountOfActiveCalls");
_STLIT8(K44, "EPhoneViewSetNaviPaneAudioVolume");
_STLIT8(K45, "EPhoneViewHideNaviPaneAudioVolume");
_STLIT8(K46, "EPhoneViewGetIsConference");
_STLIT8(K47, "EPhoneViewGetCallExistsInConference");
_STLIT8(K48, "EPhoneViewRemoveAllCallHeaders");
_STLIT8(K49, "EPhoneViewPlayRingTone");
_STLIT8(K50, "EPhoneViewMuteRingTone");
_STLIT8(K51, "EPhoneViewStopRingTone");
_STLIT8(K52, "EPhoneViewMuteRingToneOnAnswer");
_STLIT8(K53, "EPhoneViewCipheringInfoChange");
_STLIT8(K54, "EPhoneViewCloseFSW");
_STLIT8(K55, "EPhoneViewLaunchRfsDeep");
_STLIT8(K56, "EPhoneViewLaunchRfsNormal");
_STLIT8(K57, "EPhoneViewOpenSoftRejectEditor");
_STLIT8(K58, "EPhoneViewSetSecurityMode");
_STLIT8(K59, "EPhoneViewGetSecurityModeStatus");
_STLIT8(K60, "EPhoneViewEnableKeyLock");
_STLIT8(K61, "EPhoneViewEnableKeyLockWithoutNote");
_STLIT8(K62, "EPhoneViewUpdateFSW");
_STLIT8(K63, "EPhoneViewIsQuery");
_STLIT8(K64, "EPhoneViewBringIdleToForeground");
_STLIT8(K65, "EPhoneViewBeginUpdate");
_STLIT8(K66, "EPhoneViewEndUpdate");
_STLIT8(K67, "EPhoneViewRemoveConferenceBubble");
_STLIT8(K68, "EPhoneViewSetTouchPaneButtons");
_STLIT8(K69, "EPhoneViewGetBlockingDialogStatus");
_STLIT8(K70, "EPhoneViewIsNoteActive");
_STLIT8(K71, "EPhoneViewOpenCallHandling");
_STLIT8(K72, "EPhoneViewGetAudioVolumeLevel");
_STLIT8(K73, "EPhoneViewUpdateCallHeaderRemoteInfoDataAndLabel");
_STLIT8(K74, "EPhoneViewRemoveDtmfNote");
_STLIT8(K75, "EPhoneViewSetEikonNotifiersDisabled");
_STLIT8(K76, "EPhoneViewCancelAllNotications");
_STLIT8(K77, "EPhoneViewDisableKeyLock");
_STLIT8(K78, "EPhoneViewSendAiwCommand");
_STLIT8(K79, "EPhoneViewCipheringInfoChangePlayTone");
_STLIT8(K80, "EPhoneViewRemoveGlobalWaitNote");
_STLIT8(K81, "EPhoneViewSetPhoneCustomization");
_STLIT8(K82, "EPhoneViewSetViewCustomization");
_STLIT8(K83, "EPhoneViewSetButtonCustomization");
_STLIT8(K84, "EPhoneViewUpdateContactByString");
_STLIT8(K85, "EPhoneViewAddContactByString");
_STLIT8(K86, "EPhoneViewIsActiveNoteDissmissableByKeyEvent");
_STLIT8(K87, "EPhoneViewEnableToolbarButton");
_STLIT8(K88, "EPhoneViewHideToolbar");
_STLIT8(K89, "EPhoneViewShowToolbar");
_STLIT8(K90, "EPhoneViewGetExpandedBubbleCallId");
_STLIT8(K91, "EPhoneViewOpenDialer");
_STLIT8(K92, "EPhoneSetConferenceExpanded");
_STLIT8(K93, "EPhoneAppShutDown");
_STLIT8(K94, "EPhoneViewBackButtonActive");
_STLIT8(K95, "EPhoneViewHsToForegroundAfterCall");
_STLIT8(K96, "EPhoneViewOpenContacts");
_STLIT8(K97, "EPhoneViewSetIhfFlag");
_STLIT8(K98, "EPhoneViewSetMuteFlag");
_STLIT8(K99, "EPhoneViewLaunchLogs");
_STLIT8(K100, "EPhoneViewSetBlueToothFlag");
_STLIT8(K101, "EPhoneViewSetBluetoothAvailableFlag");
_STLIT8(K102, ", // Don't remove this, this should always be the last in list.");

// Intermediate
const void * const KStringPointers[] =
	{
	(const void*)&K1,
	(const void*)&K2,
	(const void*)&K3,
	(const void*)&K4,
	(const void*)&K5,
	(const void*)&K6,
	(const void*)&K7,
	(const void*)&K8,
	(const void*)&K9,
	(const void*)&K10,
	(const void*)&K11,
	(const void*)&K12,
	(const void*)&K13,
	(const void*)&K14,
	(const void*)&K15,
	(const void*)&K16,
	(const void*)&K17,
	(const void*)&K18,
	(const void*)&K19,
	(const void*)&K20,
	(const void*)&K21,
	(const void*)&K22,
	(const void*)&K23,
	(const void*)&K24,
	(const void*)&K25,
	(const void*)&K26,
	(const void*)&K27,
	(const void*)&K28,
	(const void*)&K29,
	(const void*)&K30,
	(const void*)&K31,
	(const void*)&K32,
	(const void*)&K33,
	(const void*)&K34,
	(const void*)&K35,
	(const void*)&K36,
	(const void*)&K37,
	(const void*)&K38,
	(const void*)&K39,
	(const void*)&K40,
	(const void*)&K41,
	(const void*)&K42,
	(const void*)&K43,
	(const void*)&K44,
	(const void*)&K45,
	(const void*)&K46,
	(const void*)&K47,
	(const void*)&K48,
	(const void*)&K49,
	(const void*)&K50,
	(const void*)&K51,
	(const void*)&K52,
	(const void*)&K53,
	(const void*)&K54,
	(const void*)&K55,
	(const void*)&K56,
	(const void*)&K57,
	(const void*)&K58,
	(const void*)&K59,
	(const void*)&K60,
	(const void*)&K61,
	(const void*)&K62,
	(const void*)&K63,
	(const void*)&K64,
	(const void*)&K65,
	(const void*)&K66,
	(const void*)&K67,
	(const void*)&K68,
	(const void*)&K69,
	(const void*)&K70,
	(const void*)&K71,
	(const void*)&K72,
	(const void*)&K73,
	(const void*)&K74,
	(const void*)&K75,
	(const void*)&K76,
	(const void*)&K77,
	(const void*)&K78,
	(const void*)&K79,
	(const void*)&K80,
	(const void*)&K81,
	(const void*)&K82,
	(const void*)&K83,
	(const void*)&K84,
	(const void*)&K85,
	(const void*)&K86,
	(const void*)&K87,
	(const void*)&K88,
	(const void*)&K89,
	(const void*)&K90,
	(const void*)&K91,
	(const void*)&K92,
	(const void*)&K93,
	(const void*)&K94,
	(const void*)&K95,
	(const void*)&K96,
	(const void*)&K97,
	(const void*)&K98,
	(const void*)&K99,
	(const void*)&K100,
	(const void*)&K101,
	(const void*)&K102
	};

const TStringTable PhoneLoggerviewCommands::Table = {102, KStringPointers, EFalse};

