/*
* Copyright (c) 2005 - 2010 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:  Macro definition file for logging.
*
*/

// Autogenerated from .\phoneloggerviewcommands.st by the stringtable tool - Do not edit

#ifndef STRINGTABLE_PhoneLoggerviewCommands
#define STRINGTABLE_PhoneLoggerviewCommands

#include <stringpool.h>

struct TStringTable;

/** A String table */
class PhoneLoggerviewCommands 
	{
public:
	enum TStrings
		{
		/** EPhoneViewStartValue */
		EPhoneViewStartValue,
		/** EPhoneViewCreateNumberEntry */
		EPhoneViewCreateNumberEntry,
		/** EPhoneViewSetNumberEntryContent */
		EPhoneViewSetNumberEntryContent,
		/** EPhoneViewSendKeyEventToNumberEntry */
		EPhoneViewSendKeyEventToNumberEntry,
		/** EPhoneViewRemoveNumberEntry */
		EPhoneViewRemoveNumberEntry,
		/** EPhoneViewSetNumberEntryVisible */
		EPhoneViewSetNumberEntryVisible,
		/** EPhoneViewGetNumberFromEntry */
		EPhoneViewGetNumberFromEntry,
		/** EPhoneViewGetNumberEntryCount */
		EPhoneViewGetNumberEntryCount,
		/** EPhoneViewGetNumberEntryIsUsedStatus */
		EPhoneViewGetNumberEntryIsUsedStatus,
		/** EPhoneViewGetNumberEntryIsVisibleStatus */
		EPhoneViewGetNumberEntryIsVisibleStatus,
		/** EPhoneViewToggleNumberEntryAlphaNumericMode */
		EPhoneViewToggleNumberEntryAlphaNumericMode,
		/** EPhoneViewIsNumberEntryNumericMode */
		EPhoneViewIsNumberEntryNumericMode,
		/** EPhoneViewClearNumberEntryContent */
		EPhoneViewClearNumberEntryContent,
		/** EPhoneViewCreateCallHeader */
		EPhoneViewCreateCallHeader,
		/** EPhoneViewCreateEmergencyCallHeader */
		EPhoneViewCreateEmergencyCallHeader,
		/** EPhoneViewUpdateCallHeaderRemoteInfoData */
		EPhoneViewUpdateCallHeaderRemoteInfoData,
		/** EPhoneViewUpdateCallHeaderCallDuration */
		EPhoneViewUpdateCallHeaderCallDuration,
		/** EPhoneViewRemoveCallHeader */
		EPhoneViewRemoveCallHeader,
		/** EPhoneViewMenuBarOpen */
		EPhoneViewMenuBarOpen,
		/** EPhoneViewMenuBarClose */
		EPhoneViewMenuBarClose,
		/** EPhoneViewDimCbaCommand */
		EPhoneViewDimCbaCommand,
		/** EPhoneViewUpdateCba */
		EPhoneViewUpdateCba,
		/** EPhoneViewUpdateBubble */
		EPhoneViewUpdateBubble,
		/** EPhoneViewMenuPane */
		EPhoneViewMenuPane,
		/** EPhoneViewMenuBar */
		EPhoneViewMenuBar,
		/** EPhoneViewSetTitlePaneContent */
		EPhoneViewSetTitlePaneContent,
		/** EPhoneViewSetNaviPaneContent */
		EPhoneViewSetNaviPaneContent,
		/** EPhoneViewSetTitlePanePicture */
		EPhoneViewSetTitlePanePicture,
		/** EPhoneViewGetTitlePaneIsVisibleStatus */
		EPhoneViewGetTitlePaneIsVisibleStatus,
		/** EPhoneViewActivateAudioPathUIChanges */
		EPhoneViewActivateAudioPathUIChanges,
		/** EPhoneViewActivateAudioAvailabilityUIChanges */
		EPhoneViewActivateAudioAvailabilityUIChanges,
		/** EPhoneViewActivateMuteUIChanges */
		EPhoneViewActivateMuteUIChanges,
		/** EPhoneViewShowNote */
		EPhoneViewShowNote,
		/** EPhoneViewShowGlobalNote */
		EPhoneViewShowGlobalNote,
		/** EPhoneViewShowProgressNote */
		EPhoneViewShowProgressNote,
		/** EPhoneViewRemoveNote */
		EPhoneViewRemoveNote,
		/** EPhoneViewRemoveProgressNote */
		EPhoneViewRemoveProgressNote,
		/** EPhoneViewRemoveGlobalNote */
		EPhoneViewRemoveGlobalNote,
		/** EPhoneViewGetIsNoteVisible */
		EPhoneViewGetIsNoteVisible,
		/** EPhoneViewGetIsProgressNoteVisible */
		EPhoneViewGetIsProgressNoteVisible,
		/** EPhoneViewShowQuery */
		EPhoneViewShowQuery,
		/** EPhoneViewSetListQueryString */
		EPhoneViewSetListQueryString,
		/** EPhoneViewRemoveQuery */
		EPhoneViewRemoveQuery,
		/** EPhoneViewGetTextQueryContents */
		EPhoneViewGetTextQueryContents,
		/** EPhoneViewSetTopApplication */
		EPhoneViewSetTopApplication,
		/** EPhoneViewBringAppToForeground */
		EPhoneViewBringAppToForeground,
		/** EPhoneViewSendToBackground */
		EPhoneViewSendToBackground,
		/** EPhoneViewSetNeedToSendToBackgroundStatus */
		EPhoneViewSetNeedToSendToBackgroundStatus,
		/** EPhoneViewGetNeedToSendToBackgroundStatus */
		EPhoneViewGetNeedToSendToBackgroundStatus,
		/** EPhoneViewGetTopApplicationIsDisplayedStatus */
		EPhoneViewGetTopApplicationIsDisplayedStatus,
		/** EPhoneViewGetForegroundApplication */
		EPhoneViewGetForegroundApplication,
		/** EPhoneViewSetBackgroundImageBitmap */
		EPhoneViewSetBackgroundImageBitmap,
		/** EPhoneViewGetBackgroundImageBitmap */
		EPhoneViewGetBackgroundImageBitmap,
		/** EPhoneViewActivateApp */
		EPhoneViewActivateApp,
		/** EPhoneViewActivateAppView */
		EPhoneViewActivateAppView,
		/** EPhoneViewActivateAppViewWithCustomMessage */
		EPhoneViewActivateAppViewWithCustomMessage,
		/** EPhoneViewActivateAppViewConventional */
		EPhoneViewActivateAppViewConventional,
		/** EPhoneViewLaunchApplication */
		EPhoneViewLaunchApplication,
		/** EPhoneViewLaunchHelpApplication */
		EPhoneViewLaunchHelpApplication,
		/** EPhoneViewOpenMessageEditor */
		EPhoneViewOpenMessageEditor,
		/** EPhoneViewExitApplications */
		EPhoneViewExitApplications,
		/** EPhoneViewUpdateIncallIndicator */
		EPhoneViewUpdateIncallIndicator,
		/** EPhoneViewStartCapturingKey */
		EPhoneViewStartCapturingKey,
		/** EPhoneViewStopCapturingKey */
		EPhoneViewStopCapturingKey,
		/** EPhoneViewSetGlobalNotifiersDisabled */
		EPhoneViewSetGlobalNotifiersDisabled,
		/** EPhoneViewSetSpeedDialLocation */
		EPhoneViewSetSpeedDialLocation,
		/** EPhoneViewGetNumberFromSpeedDialLocation */
		EPhoneViewGetNumberFromSpeedDialLocation,
		/** EPhoneViewAssignSpeedDialLocation */
		EPhoneViewAssignSpeedDialLocation,
		/** EPhoneViewGetHoldFlag */
		EPhoneViewGetHoldFlag,
		/** EPhoneViewSetHoldFlag */
		EPhoneViewSetHoldFlag,
		/** EPhoneViewSetSoftRejectFlag */
		EPhoneViewSetSoftRejectFlag,
		/** EPhoneViewGetSoftRejectFlag */
		EPhoneViewGetSoftRejectFlag,
		/** EPhoneViewSetServiceCodeFlag */
		EPhoneViewSetServiceCodeFlag,
		/** EPhoneViewUpdateContact */
		EPhoneViewUpdateContact,
		/** EPhoneViewAddContact */
		EPhoneViewAddContact,
		/** EPhoneViewOpenSingleItemFetchDialog */
		EPhoneViewOpenSingleItemFetchDialog,
		/** EPhoneViewRemovePhoneDialogs */
		EPhoneViewRemovePhoneDialogs,
		/** EPhoneViewCreateConference */
		EPhoneViewCreateConference,
		/** EPhoneViewAddToConference */
		EPhoneViewAddToConference,
		/** EPhoneViewRemoveFromConference */
		EPhoneViewRemoveFromConference,
		/** EPhoneViewPrivateFromConference */
		EPhoneViewPrivateFromConference,
		/** EPhoneViewSelectedConfMember */
		EPhoneViewSelectedConfMember,
		/** EPhoneViewGetConferenceListVisibleFlag */
		EPhoneViewGetConferenceListVisibleFlag,
		/** EPhoneViewOpenConferenceList */
		EPhoneViewOpenConferenceList,
		/** EPhoneViewGetCallState */
		EPhoneViewGetCallState,
		/** EPhoneViewGetCallIdByState */
		EPhoneViewGetCallIdByState,
		/** EPhoneViewMoveHighLightInList */
		EPhoneViewMoveHighLightInList,
		/** EPhoneViewGetCountOfActiveCalls */
		EPhoneViewGetCountOfActiveCalls,
		/** EPhoneViewSetNaviPaneAudioVolume */
		EPhoneViewSetNaviPaneAudioVolume,
		/** EPhoneViewShowNaviPaneAudioVolume */
		EPhoneViewShowNaviPaneAudioVolume,
		/** EPhoneViewHideNaviPaneAudioVolume */
		EPhoneViewHideNaviPaneAudioVolume,
		/** EPhoneViewGetIsConference */
		EPhoneViewGetIsConference,
		/** EPhoneViewGetCallExistsInConference */
		EPhoneViewGetCallExistsInConference,
		/** EPhoneViewRemoveAllCallHeaders */
		EPhoneViewRemoveAllCallHeaders,
		/** EPhoneViewPlayRingTone */
		EPhoneViewPlayRingTone,
		/** EPhoneViewMuteRingTone */
		EPhoneViewMuteRingTone,
		/** EPhoneViewStopRingTone */
		EPhoneViewStopRingTone,
		/** EPhoneViewMuteRingToneOnAnswer */
		EPhoneViewMuteRingToneOnAnswer,
		/** EPhoneViewCipheringInfoChange */
		EPhoneViewCipheringInfoChange,
		/** EPhoneViewUpdateMaxConfMemberFlag */
		EPhoneViewUpdateMaxConfMemberFlag,
		/** EPhoneViewCloseFSW */
		EPhoneViewCloseFSW,
		/** EPhoneViewLaunchRfsDeep */
		EPhoneViewLaunchRfsDeep,
		/** EPhoneViewLaunchRfsNormal */
		EPhoneViewLaunchRfsNormal,
		/** EPhoneViewUpdateView */
		EPhoneViewUpdateView,
		/** EPhoneViewOpenSoftRejectEditor */
		EPhoneViewOpenSoftRejectEditor,
		/** EPhoneViewSendMessage */
		EPhoneViewSendMessage,
		/** EPhoneViewSetBlockingDialogStatus */
		EPhoneViewSetBlockingDialogStatus,
		/** EPhoneViewSetPhoneNumberAvailableInPhoneEngine */
		EPhoneViewSetPhoneNumberAvailableInPhoneEngine,
		/** EPhoneViewSetStatusPaneVisible */
		EPhoneViewSetStatusPaneVisible,
		/** EPhoneViewEnableKeyLock */
		EPhoneViewEnableKeyLock,
		/** EPhoneViewLaunchFaxModem */
		EPhoneViewLaunchFaxModem,
		/** EPhoneViewUpdateFSW */
		EPhoneViewUpdateFSW,
		/** EPhoneViewIsQuery */
		EPhoneViewIsQuery,
		/** EPhoneViewBringIdleToForeground */
		EPhoneViewBringIdleToForeground,
		/** EPhoneViewSetIdleTopApplication */
		EPhoneViewSetIdleTopApplication,
		/** EPhoneViewBeginUpdate */
		EPhoneViewBeginUpdate,
		/** EPhoneViewEndUpdate */
		EPhoneViewEndUpdate,
		/** EPhoneViewSetConfrenceOptionsFlag */
		EPhoneViewSetConfrenceOptionsFlag,
		/** EPhoneViewRemoveConferenceBubble */
		EPhoneViewRemoveConferenceBubble,
		/** EPhoneViewGetSoftRejectWindowGroupId */
		EPhoneViewGetSoftRejectWindowGroupId,
		/** EPhoneViewSetTouchPaneButtons */
		EPhoneViewSetTouchPaneButtons,
		/** EPhoneViewSetTouchPaneVisible */
		EPhoneViewSetTouchPaneVisible,
		/** EPhoneViewEnableTouchButton */
		EPhoneViewEnableTouchButton,
		/** EPhoneViewDisableTouchButton */
		EPhoneViewDisableTouchButton,
		/** EPhoneResetTouchButtons */
		EPhoneResetTouchButtons,
		/** EPhoneViewGetIsConferenceInSelectionMode */
		EPhoneViewGetIsConferenceInSelectionMode,
		/** EPhoneViewIsStraightCallToVideoMailBox */
		EPhoneViewIsStraightCallToVideoMailBox,
		/** EPhoneViewSetDtmfDialerViewVisible */
		EPhoneViewSetDtmfDialerViewVisible,
		/** EPhoneViewSetRestrictedDialer */
		EPhoneViewSetRestrictedDialer,
		/** EPhoneViewIsConferenceInExpandedMode */
		EPhoneViewIsConferenceInExpandedMode,
		/** EPhoneViewIsMenuBarVisible */
		EPhoneViewIsMenuBarVisible,
		/** EPhoneViewGetBlockingDialogStatus */
		EPhoneViewGetBlockingDialogStatus,
		/** EPhoneViewYesSingleItemFetch */
		EPhoneViewYesSingleItemFetch,
		/** EPhoneViewNoSingleItemFetch */
		EPhoneViewNoSingleItemFetch,
		/** EPhoneViewGetLocalizedNumberFromEntry */
		EPhoneViewGetLocalizedNumberFromEntry,
		/** EPhoneViewIsNoteActive */
		EPhoneViewIsNoteActive,
		/** EPhoneViewOpenNumberEntry */
		EPhoneViewOpenNumberEntry,
		/** EPhoneViewOpenCallHandling */
		EPhoneViewOpenCallHandling,
		/** EPhoneViewGetConferenceAndSingleFlag */
		EPhoneViewGetConferenceAndSingleFlag,
		/** EPhoneViewSetConferenceAndSingleFlag */
		EPhoneViewSetConferenceAndSingleFlag,
		/** EPhoneViewSetVideoCallFlag */
		EPhoneViewSetVideoCallFlag,
		/** EPhoneViewSetDtmfOptionsFlag */
		EPhoneViewSetDtmfOptionsFlag,
		/** EPhoneViewShowVTSetupFailedCreateCallToSameContactQuery */
		EPhoneViewShowVTSetupFailedCreateCallToSameContactQuery,
		/** EPhoneViewGetAudioVolumeLevel */
		EPhoneViewGetAudioVolumeLevel,
		/** EPhoneViewIsIdleTopApp */
		EPhoneViewIsIdleTopApp,
		/** EPhoneViewUpdateToolbar */
		EPhoneViewUpdateToolbar,
		/** EPhoneViewSetControlAndVisibility */
		EPhoneViewSetControlAndVisibility,
		/** EPhoneViewAllowWaitingCallHeader */
		EPhoneViewAllowWaitingCallHeader,
		/** EPhoneViewBeginTransEffect */
		EPhoneViewBeginTransEffect,
		/** EPhoneViewEndTransEffect */
		EPhoneViewEndTransEffect,
		/** EPhoneViewSetDialerControlVisible */
		EPhoneViewSetDialerControlVisible,
		/** EPhoneViewCloseSingleItemFetchDialog */
		EPhoneViewCloseSingleItemFetchDialog,
		/** EPhoneViewGetActivatePreviousApp */
		EPhoneViewGetActivatePreviousApp,
		/** EPhoneViewActivatePreviousApp */
		EPhoneViewActivatePreviousApp,
		/** EPhoneViewSetPointerCapture */
		EPhoneViewSetPointerCapture,
		/** EPhoneViewSetSendKeyDialerActivationFlag */
		EPhoneViewSetSendKeyDialerActivationFlag,
		/** EPhoneViewPrepareIcons */
		EPhoneViewPrepareIcons,
		/** EPhoneViewKeypadAudioEnabled */
		EPhoneViewKeypadAudioEnabled,
		/** EPhoneViewKeypadAudioDisabled */
		EPhoneViewKeypadAudioDisabled,
		/** EPhoneViewUpdateCallHeaderRemoteInfoDataAndLabel */
		EPhoneViewUpdateCallHeaderRemoteInfoDataAndLabel,
		/** EPhoneViewRemoveDtmfNote */
		EPhoneViewRemoveDtmfNote,
		/** EPhoneViewUpdatePhoneIconToFSW */
		EPhoneViewUpdatePhoneIconToFSW,
		/** EPhoneViewSetEikonNotifiersDisabled */
		EPhoneViewSetEikonNotifiersDisabled,
		/** EPhoneViewCancelAllNotications */
		EPhoneViewCancelAllNotications,
		/** EPhoneViewSetVideoCallDTMFVisibilityFlag */
		EPhoneViewSetVideoCallDTMFVisibilityFlag,
		/** EPhoneViewLoadPlugins */
		EPhoneViewLoadPlugins,
		/** EPhoneViewOpenVirtualKeyBoard */
		EPhoneViewOpenVirtualKeyBoard,
		/** EPhoneViewUpdateNoteSoftkeys */
		EPhoneViewUpdateNoteSoftkeys,
		/** EPhoneViewSendAiwCommand */
		EPhoneViewSendAiwCommand,
		/** EPhoneViewShowCustomizedDialer */
		EPhoneViewShowCustomizedDialer,
		/** EPhoneViewHideCustomizedDialer */
		EPhoneViewHideCustomizedDialer,
		/** EPhoneViewGetCustomizedDialerMenuResourceId */
		EPhoneViewGetCustomizedDialerMenuResourceId,
		/** EPhoneViewGetCustomizedDialerCbaResourceId */
		EPhoneViewGetCustomizedDialerCbaResourceId,
		/** EPhoneViewCipheringInfoChangePlayTone */
		EPhoneViewCipheringInfoChangePlayTone,
		/** EPhoneViewCreatePhoneBookServices */
		EPhoneViewCreatePhoneBookServices,
		/** EPhoneViewDisableKeyLockWithoutNote */
		EPhoneViewDisableKeyLockWithoutNote,
		/** EPhoneViewGetKeyLockStatus */
		EPhoneViewGetKeyLockStatus,
		/** EPhoneViewSetNumberEntryObserver */
		EPhoneViewSetNumberEntryObserver,
		/** EPhoneViewGetSingleItemFetchType */
		EPhoneViewGetSingleItemFetchType,
		/** EPhoneViewRemoveGlobalWaitNote */
		EPhoneViewRemoveGlobalWaitNote,
		/** EPhoneViewSetPhoneCustomization */
		EPhoneViewSetPhoneCustomization,
		/** EPhoneViewSetViewCustomization */
		EPhoneViewSetViewCustomization,
		/** EPhoneViewSetButtonCustomization */
		EPhoneViewSetButtonCustomization,
		/** EPhoneViewUpdateContactByString */
		EPhoneViewUpdateContactByString,
		/** EPhoneViewAddContactByString */
		EPhoneViewAddContactByString,
		/** EPhoneViewIsActiveNoteDissmissableByKeyEvent */
		EPhoneViewIsActiveNoteDissmissableByKeyEvent,
		/** EPhoneViewUpdateContextMenu */
		EPhoneViewUpdateContextMenu,
		/** EPhoneViewSetNoConnectedCalls */
		EPhoneViewSetNoConnectedCalls,
		/** EPhoneViewIsDTMFEditorVisible */
		EPhoneViewIsDTMFEditorVisible,
		/** EPhoneViewSetToolbarDimming */
		EPhoneViewSetToolbarDimming,
		/** EPhoneViewEnableToolbarButton */
		EPhoneViewEnableToolbarButton,
		/** EPhoneViewHideToolbar */
		EPhoneViewHideToolbar,
		/** EPhoneViewShowToolbar */
		EPhoneViewShowToolbar,
		/** EPhoneViewGetEasyDialingInFocusStatus */
		EPhoneViewGetEasyDialingInFocusStatus,
		/** EPhoneViewSetInvalidCsPhoneNumberFlag */
		EPhoneViewSetInvalidCsPhoneNumberFlag,
		/** EPhoneViewGetInvalidCsPhoneNumberFlag */
		EPhoneViewGetInvalidCsPhoneNumberFlag,
		/** EPhoneViewGetEasyDialingMenuId */
		EPhoneViewGetEasyDialingMenuId,
		/** EPhoneViewGetEasyDialingCbaId */
		EPhoneViewGetEasyDialingCbaId,
		/** EPhoneViewGetNeedToReturnToForegroundAppStatus */
		EPhoneViewGetNeedToReturnToForegroundAppStatus,
		/** EPhoneViewSetNeedToReturnToForegroundAppStatus */
		EPhoneViewSetNeedToReturnToForegroundAppStatus,
		/** EPhoneViewSetConferenceAndWaitingVideo */
		EPhoneViewSetConferenceAndWaitingVideo,
		/** EPhoneViewLaunchMultimediaSharing */
		EPhoneViewLaunchMultimediaSharing,
		/** EPhoneViewGetQwertyModeObserver */
		EPhoneViewGetQwertyModeObserver,
		/** EPhoneViewSetIncallBubbleTrue */
		EPhoneViewSetIncallBubbleTrue,
		/** EPhoneViewSetIncallBubbleFalse */
		EPhoneViewSetIncallBubbleFalse,
		/** EPhoneViewIsDisplayingMenuOrDialog */
		EPhoneViewIsDisplayingMenuOrDialog,
		/** EPhoneViewSetQwertyModeAndOrientation */
		EPhoneViewSetQwertyModeAndOrientation,
		/** EPhoneViewIsCallWaiting */
		EPhoneViewIsCallWaiting,
		/** EPhoneViewLockCallUiOrientationIfNeeded */
		EPhoneViewLockCallUiOrientationIfNeeded,
		/** , // Don't remove this, this should always be the last in list. */
		EPhoneAmountOfCommands
		};
	static const TStringTable Table;	
	};

#endif // STRINGTABLE_PhoneLoggerviewCommands

